name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Running checks"
      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.24.0
        with:
          scan-type: fs
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
